language = 'C++23'


name = 'GCC'
version = '14.2.0-4ubuntu2~24.04'


filename = 'Main.cpp'

object = 'a.out'

execution = ['./a.out']


[[license]]
    name = 'GNU GPL v3'
    url = 'https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Copying.html'


[library.abseil]
    version = '20240722.0'
    license = [
        { name = 'Apache 2.0', url = 'https://github.com/abseil/abseil-cpp/blob/master/LICENSE' },
    ]

[library.AC-Library]
    version = '1.5.1'
    license = [
        { name = 'CC0 1.0', url = 'https://github.com/atcoder/ac-library/blob/master/LICENSE' }
    ]

[library.Boost]
    version = '1.86.0'
    license = [
        { name = 'BSL 1.0', url = 'https://www.boost.org/LICENSE_1_0.txt' }
    ]

[library.Eigen]
    version = '3.4.0-4'
    license = [
        { name = 'MPL 2.0', url = 'https://www.mozilla.org/en-US/MPL/2.0/' },
    ]

[library.GMP]
    version = '2:6.3.0+dfsg-2ubuntu6'
    license = [
        { name = 'GNU LGPL v3', url = 'https://www.gnu.org/licenses/lgpl-3.0.html' },
        { name = 'GNU GPL v2', url = 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html' }
    ]


[library.libtorch]
    version = '2.5.1'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/LICENSE'

[[library.libtorch.license]]
    name = 'Earlier BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L8-L50'

[[library.libtorch.license]]
    name = '2-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L53-L103'

[[library.libtorch.license]]
    name = 'Apache License'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L105-L285'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L287-L321'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L324-L360'

[[library.libtorch.license]]
    name = 'BSL 1.0'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L362-L418'

[[library.libtorch.license]]
    name = 'PILLOW-SIMD Software License'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L420-L456'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L458-L490'


[library.range-v3]
    version = '0.12.0'

[[library.range-v3.license]]
    name = 'BSL'
    url = 'https://github.com/ericniebler/range-v3/blob/0.12.0/LICENSE.txt#L2'

[[library.range-v3.license]]
    name = 'libc++'
    url = 'https://github.com/ericniebler/range-v3/blob/0.12.0/LICENSE.txt#L28'
    
[[library.range-v3.license]]
    name = '"Elements of Programming" license'
    url = 'https://github.com/ericniebler/range-v3/blob/0.12.0/LICENSE.txt#L107'
    
[[library.range-v3.license]]
    name = 'SGI C++ Standard Template Library license'
    url = 'https://github.com/ericniebler/range-v3/blob/0.12.0/LICENSE.txt#L127'


[library.unordered_dense]
    version = '4.4.0'
    license = [
        { name = 'MIT', url = 'https://github.com/martinus/unordered_dense/blob/main/LICENSE' },
    ]

[library.or-tools]
    version = '9.11'
    license = [
        { name = 'Apache 2.0', url = 'https://github.com/google/or-tools/blob/stable/LICENSE' },
    ]
